/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import javax.swing.JOptionPane;
import Main.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;
/**
 *
 * @author shani
 */
public class PurchaseForm extends javax.swing.JPanel {

    /**
     * Creates new form PurchaseForm
     */
    public PurchaseForm() {
        initComponents();
        loadSuppliers();
        loadProducts();
        generatePurchaseId();
    }
    
    private void generatePurchaseId() {

    try {

        Connection con = DBConnection.createConnection();

        String sql =
                "SELECT purchase_id FROM stock_purchase ORDER BY purchase_id DESC LIMIT 1";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            String lastId = rs.getString("purchase_id");

            int number = Integer.parseInt(lastId.substring(3));

            number++;

            txtPurchaseId.setText(String.format("PUR%03d", number));

        } else {

            txtPurchaseId.setText("PUR001");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
private void loadSuppliers() {

    try {

        Connection con = DBConnection.createConnection();

        String sql =
                "SELECT supplier_id, supplier_name FROM supplier ORDER BY supplier_name";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        cmbSupplier.removeAllItems();

        while (rs.next()) {

            cmbSupplier.addItem(
                    rs.getString("supplier_id")
                    + " - "
                    + rs.getString("supplier_name")
            );

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
   private void loadProducts() {

    try {

        Connection con = DBConnection.createConnection();

        String sql =
                "SELECT product_id, product_name FROM product ORDER BY product_name";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        cmbProduct.removeAllItems();

        while (rs.next()) {

            cmbProduct.addItem(
                    rs.getString("product_id")
                    + " - "
                    + rs.getString("product_name")
            );

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
   private void calculateGrandTotal() {

    double grandTotal = 0;

    for (int i = 0; i < tblPurchase.getRowCount(); i++) {

        grandTotal += Double.parseDouble(
                tblPurchase.getValueAt(i, 4).toString());

    }

    txtGrandTotal.setText(String.format("%.2f", grandTotal));

}
private int getNextPurchaseDetailNumber(Connection con) throws Exception {

    String sql =
            "SELECT purchase_detail_id "
            + "FROM stock_purchase_details "
            + "ORDER BY purchase_detail_id DESC LIMIT 1";

    PreparedStatement pst = con.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {

        String lastId = rs.getString("purchase_detail_id");

        return Integer.parseInt(lastId.substring(3)) + 1;

    }

    return 1;

}
private void clearPurchaseForm() {

    txtBuyingPrice.setText("");
    txtQuantity.setText("");
    txtGrandTotal.setText("");

    cmbSupplier.setSelectedIndex(0);
    cmbProduct.setSelectedIndex(0);

    DefaultTableModel model =
            (DefaultTableModel) tblPurchase.getModel();

    model.setRowCount(0);

}
private void clearFields() {

    generatePurchaseId();

    txtBuyingPrice.setText("");
    txtQuantity.setText("");
    txtGrandTotal.setText("");

    cmbSupplier.setSelectedIndex(0);
    cmbProduct.setSelectedIndex(0);

    DefaultTableModel model =
            (DefaultTableModel) tblPurchase.getModel();

    model.setRowCount(0);

    tblPurchase.clearSelection();

    cmbSupplier.requestFocus();

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPurchaseId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dcPurchaseDate = new datechooser.beans.DateChooserCombo();
        jLabel3 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbProduct = new javax.swing.JComboBox<>();
        txtBuyingPrice = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPurchase = new javax.swing.JTable();
        btnSavePurchase = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtGrandTotal = new javax.swing.JTextField();

        jLabel1.setText("Purchase ID");

        txtPurchaseId.setEditable(false);

        jLabel2.setText("Purchase Date");

        jLabel3.setText("Supplier");

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Product");

        jLabel5.setText("Buying Price");

        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Quantity");

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(this::btnAddItemActionPerformed);

        tblPurchase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Buying Price", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblPurchase);

        btnSavePurchase.setText("Save");
        btnSavePurchase.addActionListener(this::btnSavePurchaseActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        jLabel7.setText("Grand Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSavePurchase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnClear))
                    .addComponent(btnAddItem)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPurchaseId)
                            .addComponent(dcPurchaseDate, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                            .addComponent(cmbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtBuyingPrice)
                            .addComponent(txtQuantity)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPurchaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(dcPurchaseDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBuyingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSavePurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        
    String selectedProduct = cmbProduct.getSelectedItem().toString();

    String productId = selectedProduct.split(" - ")[0];
    String productName = selectedProduct.split(" - ")[1];

    double buyingPrice = Double.parseDouble(txtBuyingPrice.getText());

    int quantity = Integer.parseInt(txtQuantity.getText());

    double subtotal = buyingPrice * quantity;

    DefaultTableModel model = (DefaultTableModel) tblPurchase.getModel();

    model.addRow(new Object[]{

        productId,
        productName,
        buyingPrice,
        quantity,
        subtotal

    });

    calculateGrandTotal();

    txtBuyingPrice.setText("");
    txtQuantity.setText("");

    cmbProduct.requestFocus();

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnSavePurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePurchaseActionPerformed
        
        try{
        String selectedSupplier = cmbSupplier.getSelectedItem().toString();

        String supplierId = selectedSupplier.split(" - ")[0];
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String purchaseDate = sdf.format(dcPurchaseDate.getSelectedDate().getTime());
        
        double totalAmount = Double.parseDouble(txtGrandTotal.getText());
        
        Connection con = DBConnection.createConnection();
        
        con.setAutoCommit(false);
        int detailNo = getNextPurchaseDetailNumber(con);

        String sql =
        "INSERT INTO stock_purchase "
        + "(purchase_id,supplier_id,purchase_date,total_amount) "
        + "VALUES (?,?,?,?)";

        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, txtPurchaseId.getText());
        pst.setString(2, supplierId);
        pst.setString(3, purchaseDate);
        pst.setDouble(4, totalAmount);

        int result = pst.executeUpdate();
        
        if(result > 0){

    DefaultTableModel model =
            (DefaultTableModel) tblPurchase.getModel();

    for(int i = 0; i < model.getRowCount(); i++){
        
        String purchaseDetailId =
        String.format("PDT%03d", detailNo);
        detailNo++;

        String productId =
                model.getValueAt(i,0).toString();

        double buyingPrice =
                Double.parseDouble(
                        model.getValueAt(i,2).toString());

        int quantity =
                Integer.parseInt(
                        model.getValueAt(i,3).toString());

        double subtotal =
                Double.parseDouble(
                        model.getValueAt(i,4).toString());
                        
        
        
        String sql2 =
                "INSERT INTO stock_purchase_details "
                + "(purchase_detail_id,"
                + "purchase_id,"
                + "product_id,"
                + "quantity,"
                + "buying_price,"
                + "subtotal)"
                + " VALUES (?,?,?,?,?,?)";

        PreparedStatement pst2 = con.prepareStatement(sql2);

        pst2.setString(1,purchaseDetailId);
        pst2.setString(2,txtPurchaseId.getText());
        pst2.setString(3,productId);
        pst2.setInt(4,quantity);
        pst2.setDouble(5,buyingPrice);
        pst2.setDouble(6,subtotal);

        pst2.executeUpdate();
        
        String sql3 =
        "UPDATE product "
        + "SET stock_qty = stock_qty + ? "
        + "WHERE product_id = ?";

        PreparedStatement pst3 = con.prepareStatement(sql3);

        pst3.setInt(1, quantity);
        pst3.setString(2, productId);

        pst3.executeUpdate();

    }
    if(result > 0){
        con.commit();

        JOptionPane.showMessageDialog(this,"Purchase Saved Successfully!");
    }
    clearPurchaseForm();

    generatePurchaseId();
    

}

        }
        catch (Exception e) {

            Connection con = null;
            if (con != null) {
        try {
            con.rollback();
        } catch (Exception ex) {
            ex.printStackTrace();
            
        }
    }

    JOptionPane.showMessageDialog(
            this,
            "Error while saving purchase!\n" + e.getMessage()
    );

    e.printStackTrace();

}
        
        
    }//GEN-LAST:event_btnSavePurchaseActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       clearFields();
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSavePurchase;
    private javax.swing.JComboBox<String> cmbProduct;
    private javax.swing.JComboBox<String> cmbSupplier;
    private datechooser.beans.DateChooserCombo dcPurchaseDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPurchase;
    private javax.swing.JTextField txtBuyingPrice;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtPurchaseId;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
