/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Views;
import javax.swing.JOptionPane;
import Main.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author shani
 */
public class SalesForm extends javax.swing.JPanel {
private String userId;
    /**
     * Creates new form SalesForm
     */
    public SalesForm() {
        initComponents();
    }
public SalesForm(String userId) {

    initComponents();

    this.userId = userId;

    generateSaleId();
    loadCustomers();
    loadProducts();

}
private void generateSaleId() {

    try {

        Connection con = DBConnection.createConnection();

        String sql =
                "SELECT sale_id FROM sales ORDER BY sale_id DESC LIMIT 1";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            String lastId = rs.getString("sale_id");

            int number = Integer.parseInt(lastId.substring(3));

            number++;

            txtSaleId.setText(String.format("SAL%03d", number));

        } else {

            txtSaleId.setText("SAL001");

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
private void loadCustomers() {

    try {

        Connection con = DBConnection.createConnection();

        String sql =
                "SELECT customer_id, customer_name "
                + "FROM customer ORDER BY customer_name";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        cmbCustomer.removeAllItems();

        while (rs.next()) {

            cmbCustomer.addItem(
                    rs.getString("customer_id")
                    + " - "
                    + rs.getString("customer_name")
            );

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
private void loadProducts() {

    try {

        Connection con = DBConnection.createConnection();

        String sql =
                "SELECT product_id, product_name "
                + "FROM product "
                + "ORDER BY product_name";

        PreparedStatement pst = con.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        cmbProduct.removeAllItems();

        while (rs.next()) {

            cmbProduct.addItem(
                    rs.getString("product_id")
                    + " - "
                    + rs.getString("product_name")
            );

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, e.getMessage());

    }

}
private void calculateGrandTotal() {

    double grandTotal = 0;

    DefaultTableModel model =
            (DefaultTableModel) tblSales.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {

        Object value = model.getValueAt(i, 4);

        if (value != null) {

            grandTotal += Double.parseDouble(value.toString());

        }

    }

    txtGrandTotal.setText(
            String.format("%.2f", grandTotal));

}
private int getNextSaleDetailNumber(Connection con) throws Exception {

    String sql =
            "SELECT sale_detail_id "
            + "FROM sales_details "
            + "ORDER BY sale_detail_id DESC LIMIT 1";

    PreparedStatement pst = con.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {

        String lastId = rs.getString("sale_detail_id");

        return Integer.parseInt(lastId.substring(3)) + 1;

    }

    return 1;

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSaleId = new javax.swing.JTextField();
        txtSellingPrice = new javax.swing.JTextField();
        txtAvailableStock = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtGrandTotal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbProduct = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        dcSaleDate = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        jLabel1.setText("Sales ID");

        jLabel2.setText("Selling Price");

        jLabel3.setText("Available Stock");

        jLabel4.setText("Quantity");

        jLabel5.setText("Grand Total");

        txtSaleId.setEditable(false);

        txtSellingPrice.setEditable(false);

        txtAvailableStock.setEditable(false);

        jLabel6.setText("Customer");

        jLabel7.setText("Product");

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cmbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProduct.addActionListener(this::cmbProductActionPerformed);

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Selling Price", "Quantity", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(tblSales);

        jLabel8.setText("Date");

        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(this::btnAddItemActionPerformed);

        btnSave.setText("Save");
        btnSave.addActionListener(this::btnSaveActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtSaleId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtQuantity))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtGrandTotal))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtAvailableStock)
                                        .addComponent(txtSellingPrice)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbProduct, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dcSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbCustomer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnAddItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSave)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSaleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSellingPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAvailableStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGrandTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcSaleDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductActionPerformed
       
        try {

    if (cmbProduct.getSelectedItem() == null) {
        return;
    }

    String selectedProduct = cmbProduct.getSelectedItem().toString();

    String productId = selectedProduct.split(" - ")[0];

    Connection con = DBConnection.createConnection();

    String sql =
            "SELECT selling_price, stock_qty "
            + "FROM product "
            + "WHERE product_id=?";

    PreparedStatement pst = con.prepareStatement(sql);

    pst.setString(1, productId);

    ResultSet rs = pst.executeQuery();

    if (rs.next()) {

        txtSellingPrice.setText(rs.getString("selling_price"));

        txtAvailableStock.setText(rs.getString("stock_qty"));

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(this, e.getMessage());

}
    }//GEN-LAST:event_cmbProductActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        
    String selectedProduct = cmbProduct.getSelectedItem().toString();

    String productId = selectedProduct.split(" - ")[0];
    String productName = selectedProduct.split(" - ")[1];
    
    double sellingPrice = Double.parseDouble(txtSellingPrice.getText());
    int availableStock = Integer.parseInt(txtAvailableStock.getText());
    int quantity = Integer.parseInt(txtQuantity.getText());
    
     if (quantity > availableStock) {

        JOptionPane.showMessageDialog(
                this,
                "Insufficient stock available!"
        );

        txtQuantity.requestFocus();

        return;

    }
     
 
    double subtotal = sellingPrice * quantity;


    DefaultTableModel model =
            (DefaultTableModel) tblSales.getModel();

    model.addRow(new Object[]{
        productId,
        productName,
        sellingPrice,
        quantity,
        subtotal
    });


    calculateGrandTotal();


    txtQuantity.setText("");

    cmbProduct.requestFocus();

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        Connection con = null;

try {


    String selectedCustomer = cmbCustomer.getSelectedItem().toString();
    String customerId = selectedCustomer.split(" - ")[0];


    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String saleDate = sdf.format(dcSaleDate.getSelectedDate().getTime());


    double totalAmount = Double.parseDouble(txtGrandTotal.getText());


    con = DBConnection.createConnection();


    con.setAutoCommit(false);


    int detailNo = getNextSaleDetailNumber(con);
    
    String sql =
        "INSERT INTO sales "
        + "(sale_id, customer_id, user_id, sale_date, total_amount) "
        + "VALUES (?,?,?,?,?)";

PreparedStatement pst = con.prepareStatement(sql);

pst.setString(1, txtSaleId.getText());
pst.setString(2, customerId);
pst.setString(3, userId);
pst.setString(4, saleDate);
pst.setDouble(5, totalAmount);

int result = pst.executeUpdate();

if(result > 0){

    DefaultTableModel model =
            (DefaultTableModel) tblSales.getModel();

    for(int i = 0; i < model.getRowCount(); i++){

        String saleDetailId =
                String.format("SDT%03d", detailNo);

        detailNo++;

        String productId =
                model.getValueAt(i,0).toString();

        double unitPrice =
                Double.parseDouble(
                        model.getValueAt(i,2).toString());

        int quantity =
                Integer.parseInt(
                        model.getValueAt(i,3).toString());

        double subtotal =
                Double.parseDouble(
                        model.getValueAt(i,4).toString());

        String sql2 =
                "INSERT INTO sales_details "
                + "(sale_detail_id, sale_id, product_id, quantity, unit_price, subtotal) "
                + "VALUES (?,?,?,?,?,?)";

        PreparedStatement pst2 =
                con.prepareStatement(sql2);

        pst2.setString(1, saleDetailId);
        pst2.setString(2, txtSaleId.getText());
        pst2.setString(3, productId);
        pst2.setInt(4, quantity);
        pst2.setDouble(5, unitPrice);
        pst2.setDouble(6, subtotal);

        pst2.executeUpdate();

        String sql3 =
                "UPDATE product "
                + "SET stock_qty = stock_qty - ? "
                + "WHERE product_id = ?";

        PreparedStatement pst3 =
                con.prepareStatement(sql3);

        pst3.setInt(1, quantity);
        pst3.setString(2, productId);

        pst3.executeUpdate();

        pst2.close();
        pst3.close();
    }

    con.commit();

    JOptionPane.showMessageDialog(
            this,
            "Sale Saved Successfully!"
    );

    pst.close();

    con.setAutoCommit(true);
    con.close();

}


} catch (Exception e) {

    if (con != null) {
        try {
            con.rollback();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    JOptionPane.showMessageDialog(this,
            "Error : " + e.getMessage());

    e.printStackTrace();
}
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbProduct;
    private datechooser.beans.DateChooserCombo dcSaleDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSales;
    private javax.swing.JTextField txtAvailableStock;
    private javax.swing.JTextField txtGrandTotal;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSaleId;
    private javax.swing.JTextField txtSellingPrice;
    // End of variables declaration//GEN-END:variables
}
